import type { BilingualOrder, ExportVariant, SubtitleDocument } from './models';

const ASS_PLAY_RES_X = 1920;
const ASS_PLAY_RES_Y = 1080;
const ASS_MARGIN_L = 88;
const ASS_MARGIN_R = 88;
const ASS_MARGIN_V = 34;
const ASS_MAX_TEXT_WIDTH = ASS_PLAY_RES_X - ASS_MARGIN_L - ASS_MARGIN_R;
const TRANSLATED_BASE_SIZE = 30;
const SOURCE_BASE_SIZE = 20;
const MIN_TRANSLATED_SIZE = 10;
const MIN_SOURCE_SIZE = 8;

export type SerializeAssOptions = {
  variant?: ExportVariant;
  bilingualOrder?: BilingualOrder;
  allowEmpty?: boolean;
};

export function serializeAss(document: SubtitleDocument, options: SerializeAssOptions = {}): string {
  const variant = options.variant ?? 'translated';
  const bilingualOrder = options.bilingualOrder ?? 'source-first';
  const sorted = [...document.segments].sort((a, b) => a.startMs - b.startMs || a.index - b.index);

  const dialogues = sorted.map((segment) => {
    const text = dialogueTextForVariant(segment.sourceText, segment.translatedText, variant, bilingualOrder);
    if (!options.allowEmpty && !stripAssFormatting(text).trim()) {
      throw new Error(`Cannot export empty subtitle segment ${segment.id}.`);
    }
    return `Dialogue: 0,${formatAssTimestamp(segment.startMs)},${formatAssTimestamp(segment.endMs)},Default,,0,0,0,,${text}`;
  });

  return [
    '[Script Info]',
    '; Generated by Translate-Ter',
    'ScriptType: v4.00+',
    'WrapStyle: 2',
    'ScaledBorderAndShadow: yes',
    'YCbCr Matrix: TV.709',
    `PlayResX: ${ASS_PLAY_RES_X}`,
    `PlayResY: ${ASS_PLAY_RES_Y}`,
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    `Style: Default,Microsoft YaHei,${TRANSLATED_BASE_SIZE},&H00FFFFFF,&H000000FF,&H6E101418,&H96000000,0,0,0,0,100,100,0,0,1,1.8,0.6,2,${ASS_MARGIN_L},${ASS_MARGIN_R},${ASS_MARGIN_V},1`,
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
    ...dialogues,
    ''
  ].join('\n');
}

export function formatAssTimestamp(ms: number): string {
  if (!Number.isInteger(ms) || ms < 0) {
    throw new Error(`Invalid timestamp: ${ms}`);
  }

  const hours = Math.floor(ms / 3_600_000);
  const minutes = Math.floor((ms % 3_600_000) / 60_000);
  const seconds = Math.floor((ms % 60_000) / 1_000);
  const centiseconds = Math.floor((ms % 1_000) / 10);
  return `${hours}:${pad(minutes, 2)}:${pad(seconds, 2)}.${pad(centiseconds, 2)}`;
}

function dialogueTextForVariant(
  sourceText: string,
  translatedText: string | undefined,
  variant: ExportVariant,
  bilingualOrder: BilingualOrder
): string {
  const source = collapseSubtitleLine(sourceText);
  const translated = collapseSubtitleLine(translatedText ?? '');

  if (variant === 'source') {
    return buildSourceLine(source, SOURCE_BASE_SIZE, MIN_SOURCE_SIZE);
  }

  if (variant === 'translated') {
    const primary = translated || source;
    return buildTranslatedLine(primary, TRANSLATED_BASE_SIZE, MIN_TRANSLATED_SIZE);
  }

  const translatedSize = fitFontSize(translated, TRANSLATED_BASE_SIZE, MIN_TRANSLATED_SIZE);
  const sourceBaseSize = Math.min(SOURCE_BASE_SIZE, Math.max(MIN_SOURCE_SIZE, translatedSize - 8));
  const orderedLines =
    bilingualOrder === 'source-first'
      ? [
          buildSourceLine(source, sourceBaseSize, MIN_SOURCE_SIZE),
          buildTranslatedLine(translated, translatedSize, MIN_TRANSLATED_SIZE)
        ]
      : [
          buildTranslatedLine(translated, translatedSize, MIN_TRANSLATED_SIZE),
          buildSourceLine(source, sourceBaseSize, MIN_SOURCE_SIZE)
        ];

  return orderedLines.filter(Boolean).join('\\N');
}

function buildTranslatedLine(text: string, baseSize: number, minSize: number): string {
  const collapsed = collapseSubtitleLine(text);
  if (!collapsed) return '';
  const fontSize = fitFontSize(collapsed, baseSize, minSize);
  return `{\\q2\\fs${fontSize}\\b1\\c&HFFFFFF&}${escapeAssText(collapsed)}`;
}

function buildSourceLine(text: string, baseSize: number, minSize: number): string {
  const collapsed = collapseSubtitleLine(text);
  if (!collapsed) return '';
  const fontSize = fitFontSize(collapsed, baseSize, minSize);
  return `{\\q2\\fs${fontSize}\\b0\\c&HCFD6DE&\\alpha&H18&}${escapeAssText(collapsed)}`;
}

function fitFontSize(text: string, baseSize: number, minSize: number): number {
  const collapsed = collapseSubtitleLine(text);
  if (!collapsed) return baseSize;
  const estimatedWidth = estimateTextUnits(collapsed) * baseSize;
  if (estimatedWidth <= ASS_MAX_TEXT_WIDTH) {
    return baseSize;
  }
  return Math.max(minSize, Math.floor((ASS_MAX_TEXT_WIDTH / estimatedWidth) * baseSize));
}

function estimateTextUnits(text: string): number {
  let units = 0;
  for (const char of text) {
    if (/\s/.test(char)) {
      units += 0.32;
      continue;
    }
    if (/[A-Z]/.test(char)) {
      units += 0.76;
      continue;
    }
    if (/[a-z0-9]/.test(char)) {
      units += 0.62;
      continue;
    }
    if (/[\u3040-\u30ff\u3400-\u9fff\uf900-\ufaff\uac00-\ud7af]/.test(char)) {
      units += 1.04;
      continue;
    }
    if (/[,.;:!?'"，。！？；：（）()\-]/.test(char)) {
      units += 0.42;
      continue;
    }
    units += 0.95;
  }
  return Math.max(1, units);
}

function collapseSubtitleLine(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}

function escapeAssText(text: string): string {
  return collapseSubtitleLine(text).replace(/{/g, '\\{').replace(/}/g, '\\}');
}

function stripAssFormatting(text: string): string {
  return text.replace(/\{[^}]*\}/g, '').replace(/\\N/g, '\n');
}

function pad(value: number, length: number): string {
  return String(value).padStart(length, '0');
}
